Move C_ASSERT outside of struct (#31)
I moved the C_ASSERT outside of the `DETOUR_EXE_RESTORE` struct definition because it expands into a typedef (which I believe isn't valid C) and causes this compilation error if you include `detours.h` in a C program or library:

```
detours.h(390): error C2071: '__C_ASSERT__': illegal storage class
```